name: Deploy Compose

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # 코드 클론
        uses: actions/checkout@v4

      - name: Copy directory to Server
        id: copy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          source: "docker/*"
          target: /home/chlowoomin/

      - name: Deploy the app # 배포중 메시지 출력
        run: echo "Deploying the app..."
      - name: 확인용 디버깅 - 파일 목록 출력
        run: |
          echo "==== 현재 경로 ===="
          pwd
          echo "==== 현재 디렉토리의 파일들 ===="
          ls -al
      
      - name: Deploy to Server # 복사된 docker-compose.yml 파일을 실행
        id: deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            pwd
            ls -al
            docker compose pull & docker compose up -d # 서비스 실행

      - name: Clean Up Files in Server # 이후 docker-compose.yml 파일 삭제
        if: always()
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -f /home/chlowoomin/docker-compose.yml